---
- name: Initialize Rendertron
  hosts: rendertronservers
  become: yes
  become_method: sudo
  tasks:
  - name: Run the equivalent of "apt-get update"
    apt:
      update_cache: yes
  - name: Update all packages to the latest version
    apt:
      upgrade: dist
...