---
- name: Initialize Rendertron
  hosts: rendertronservers
  become: yes
  tasks:
  - include_role:
      name: common
  - include_role:
      name: nodejs_8.x
  - include_role:
      name: docker
  # - include_role:
  #     name: rendertronRepo
...