---
- name: Initialize Test
  hosts: testservers
  become: yes
  tasks:
  - include_role:
      name: common
  - include_role:
      name: nodejs
      vars:
        version: 8
  - include_role:
      name: test
...