---
- name: Download nodejs v8.x script
  get_url:
    url: https://deb.nodesource.com/setup_8.x
    dest: /tmp/setup_8.x

- name: Run nodejs v8.x script
  shell: bash /tmp/setup_8.x
  become: yes

- name: Install nodejs
  apt:
    name: nodejs
    state: present
    update_cache: yes
...