---
- name: Download gongga source
  git:
    repo: git@github.com:wego/gongga.git
    dest: github/gongga/
    update: yes

- name: Install packages based on package.json.
  npm:
    path: github/gongga/
    state: present

- name: Install packages based on bower.json.
  bower:
    path: github/gongga/
    state: present

- name: Build polymer components
  shell: polymer build
  args:
    chdir: github/gongga/

- name: Add gonggo service systemd configuration
  copy:
    src: gongga.service
    dest: /etc/systemd/system/
    mode: 0644

- name: Start gonggo service
  systemd:
    name: gongga
    enabled: yes
    daemon_reload: yes
    state: started
...