---
- name: Remove older versions of docker
  apt:
    name: "{{ item }}"
    state: absent
  loop:
    - docker
    - docker-engine
    - docker.io

- name: Add docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- debug:
  msg: "{{ ansible_distribution }}"
...